# Generated by Django 5.0.1 on 2024-01-28 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('ProID', models.AutoField(primary_key=True, serialize=False)),
                ('ProName', models.CharField(max_length=250)),
                ('ProDescription', models.CharField(max_length=250)),
                ('ProCapacity', models.IntegerField()),
            ],
            options={
                'db_table': 'program',
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('SCID', models.AutoField(primary_key=True, serialize=False)),
                ('Coursework', models.IntegerField()),
                ('Exam', models.IntegerField()),
            ],
            options={
                'db_table': 'studentcourse',
            },
        ),
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'todos',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CoID', models.AutoField(primary_key=True, serialize=False)),
                ('CoTitle', models.CharField(max_length=250)),
                ('CoCode', models.CharField(max_length=250)),
                ('Coursework', models.IntegerField()),
                ('Exam', models.IntegerField()),
                ('ProID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.program')),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StuID', models.AutoField(primary_key=True, serialize=False)),
                ('ProID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academics.program')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
