# Generated by Django 5.0.1 on 2024-01-28 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='UserID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='CoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='StuID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.student'),
        ),
    ]
