# Generated by Django 5.0 on 2023-12-30 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StuID', models.AutoField(primary_key=True, serialize=False)),
                ('StuName', models.CharField(max_length=250)),
                ('StuPhone', models.CharField(max_length=10)),
                ('StuAddress', models.CharField(max_length=250)),
                ('ProID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.program')),
                ('UserID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academics.user')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
