# Generated by Django 5.0 on 2023-12-30 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('SCID', models.AutoField(primary_key=True, serialize=False)),
                ('Coursework', models.IntegerField()),
                ('Exam', models.IntegerField()),
                ('CoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
                ('StuID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.student')),
            ],
            options={
                'db_table': 'studentcourse',
            },
        ),
    ]
