# Generated by Django 5.0.4 on 2024-05-17 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_remove_course_proid_remove_studentcourse_coid_and_more'),
        ('account', '0005_remove_user_regno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('ResearchID', models.AutoField(primary_key=True, serialize=False)),
                ('DocumentType', models.CharField(choices=[('CN', 'ConceptNote'), ('PS', 'Proposal'), ('PR', 'ProgresReport')], max_length=100)),
                ('Document', models.FileField(upload_to='documents')),
                ('Status', models.CharField(choices=[('NW', 'NEW'), ('PR', 'PROGRES'), ('CO', 'COMPLETED')], default='NW', max_length=2)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'research',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('RID', models.AutoField(primary_key=True, serialize=False)),
                ('Grade', models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2)),
                ('ResearchID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academics.research')),
            ],
            options={
                'db_table': 'grade',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('StaffID', models.AutoField(primary_key=True, serialize=False)),
                ('Role', models.CharField(choices=[('Supervisor', 'Supervisor'), ('InternalExaminer', 'InternalExaminer'), ('PGO', 'PostGraduateOfficer'), ('Admin', 'Admin')], max_length=100)),
                ('UserID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StuID', models.AutoField(primary_key=True, serialize=False)),
                ('Program', models.CharField(choices=[('BITAM', 'BACHELOR OF IT APPLICATION AND MANAGEMENT'), ('BCS', 'BACHELOR OF SCIENCE IN COMPUTER SCIENCE'), ('BAGES', 'BACHELOR OF ART IN GEORGRAPHY AND ENVIRONMENTAL STUDIES')], max_length=10)),
                ('RegNo', models.CharField(max_length=250, unique=True)),
                ('StaffID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.staff')),
                ('UserID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.AddField(
            model_name='research',
            name='StuID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academics.student'),
        ),
    ]
