# Generated by Django 5.0.6 on 2024-05-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_result_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='Title',
            field=models.CharField(default='k', max_length=250),
            preserve_default=False,
        ),
    ]
