# Generated by Django 5.0 on 2024-01-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='StuAddress',
        ),
        migrations.RemoveField(
            model_name='student',
            name='StuName',
        ),
        migrations.RemoveField(
            model_name='student',
            name='StuPhone',
        ),
        migrations.AddField(
            model_name='user',
            name='Address',
            field=models.CharField(default='Fuoni', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='PhoneNumber',
            field=models.CharField(default='0773788543', max_length=10),
            preserve_default=False,
        ),
    ]
