# Generated by Django 5.0.6 on 2024-05-20 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_research_title'),
        ('account', '0005_remove_user_regno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='StaffID',
        ),
        migrations.AlterField(
            model_name='research',
            name='DocumentType',
            field=models.CharField(choices=[('concept_note', 'ConceptNote'), ('proposal', 'Proposal'), ('progres_report', 'ProgresReport')], max_length=100),
        ),
        migrations.AlterField(
            model_name='research',
            name='Status',
            field=models.CharField(choices=[('new', 'NEW'), ('progress', 'PROGRES'), ('completed', 'COMPLETED')], default='new', max_length=100),
        ),
        migrations.CreateModel(
            name='Examiner',
            fields=[
                ('ExID', models.AutoField(primary_key=True, serialize=False)),
                ('UserID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'db_table': 'Examiner',
            },
        ),
        migrations.AddField(
            model_name='recommendation',
            name='ExID',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.examiner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='ExID',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.examiner'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PostGraduateOfficer',
            fields=[
                ('PgoID', models.AutoField(primary_key=True, serialize=False)),
                ('UserID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'db_table': 'postGraduateOfficer',
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('SupID', models.AutoField(primary_key=True, serialize=False)),
                ('UserID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'db_table': 'Supervisor',
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('AID', models.AutoField(primary_key=True, serialize=False)),
                ('StuID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academics.student')),
                ('ExID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academics.examiner')),
                ('SupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.supervisor')),
            ],
            options={
                'db_table': 'allocation',
            },
        ),
        migrations.AddField(
            model_name='recommendation',
            name='SupID',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.supervisor'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
