# Generated by Django 5.0.1 on 2024-01-18 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_remove_student_stuaddress_remove_student_stuname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='StuID',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='CoID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentCourse',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
