# Generated by Django 5.0.6 on 2024-05-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_remove_student_staffid_alter_research_documenttype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='ExID',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='SupID',
        ),
        migrations.RemoveField(
            model_name='result',
            name='ExID',
        ),
    ]
