# Generated by Django 5.0.1 on 2024-01-18 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_remove_studentcourse_stuid_remove_studentcourse_coid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StuID', models.AutoField(primary_key=True, serialize=False)),
                ('ProID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academics.program')),
                ('UserID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('SCID', models.AutoField(primary_key=True, serialize=False)),
                ('Coursework', models.IntegerField()),
                ('Exam', models.IntegerField()),
                ('CoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
                ('StuID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.student')),
            ],
            options={
                'db_table': 'studentcourse',
            },
        ),
    ]
