# Generated by Django 5.0.6 on 2024-05-25 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_remove_recommendation_exid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='ExID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.examiner'),
        ),
    ]
