# Generated by Django 5.0.6 on 2024-06-20 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_alter_allocation_exid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='examiner',
            table='examiner',
        ),
        migrations.AlterModelTable(
            name='supervisor',
            table='supervisor',
        ),
    ]
