# Generated by Django 5.0.4 on 2024-05-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='RegNo',
            field=models.CharField(default='jkj', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
