# Generated by Django 5.0.6 on 2024-05-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_regno'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_PGO',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_examiner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_supevisor',
            field=models.BooleanField(default=False),
        ),
    ]
