# Generated by Django 5.0.6 on 2024-05-21 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
